 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: A2016                                                       
     # Surfaces =   4
     # Strips   =  48
     # Vortices = 384

  Sref =  1.2549       Cref = 0.50000       Bref =  1.8679    
  Xref =-0.38919       Yref =  0.0000       Zref = 0.21486    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06084     Cltot =  -0.00000     Cl'tot =   0.00000
  CYtot =  -0.00005     Cmtot =  -0.01334
  CZtot =  -1.13028     Cntot =   0.00001     Cn'tot =   0.00001

  CLtot =   1.12367
  CDtot =   0.13635
  CDvis =   0.00000     CDind =   0.13635
  CLff  =   1.14699     CDff  =   0.15193    | Trefftz
  CYff  =   0.00000         e =    0.9913    | Plane  


 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   2.428305    CLb =   0.000009
 y  force CY |    CYa =  -0.000220    CYb =  -0.278654
 x' mom.  Cl'|    Cla =   0.000007    Clb =  -0.175585
 y  mom.  Cm |    Cma =  -0.121837    Cmb =  -0.000019
 z' mom.  Cn'|    Cna =   0.000026    Cnb =   0.059523

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000003    CLq =   3.867526    CLr =  -0.000005
 y  force CY |    CYp =   0.488917    CYq =  -0.000131    CYr =   0.063601
 x' mom.  Cl'|    Clp =  -0.233915    Clq =   0.000002    Clr =   0.236729
 y  mom.  Cm |    Cmp =  -0.000009    Cmq =  -3.165618    Cmr =   0.000014
 z' mom.  Cn'|    Cnp =  -0.122946    Cnq =   0.000023    Cnr =  -0.041051

 Neutral point  Xnp =  -0.364104

 Clb Cnr / Clr Cnb  =   0.511530    (  > 1 if spirally stable )
