 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: A2016                                                       
     # Surfaces =   4
     # Strips   =  96
     # Vortices =1152

  Sref =  1.0901       Cref = 0.35000       Bref =  2.0323    
  Xref =-0.14182       Yref =  0.0000       Zref = 0.14156    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.03587     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -0.60127
  CZtot =  -0.75628     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.75336
  CDtot =   0.07541
  CDvis =   0.00000     CDind =   0.07541
  CLff  =   0.75731     CDff  =   0.07610    | Trefftz
  CYff  =   0.00000         e =    0.6331    | Plane  


 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   3.115226    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =   0.000000
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.074702
 y  mom.  Cm |    Cma =   0.637414    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.003915

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   4.667122    CLr =  -0.000000
 y  force CY |    CYp =   0.149403    CYq =  -0.000000    CYr =  -0.007830
 x' mom.  Cl'|    Clp =  -0.276877    Clq =   0.000000    Clr =   0.128666
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -12.080469    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.040586    Cnq =  -0.000000    Cnr =  -0.009291

 Neutral point  Xnp =  -0.213435

 Clb Cnr / Clr Cnb  =   1.377916    (  > 1 if spirally stable )
